set -g default-terminal "xterm-256color"
setw -g xterm-keys on
set -s escape-time 5
set -sg repeat-time 600
set -s focus-events on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind-key m set -g mouse\; display-message "mouse mod is now #{?mouse,on,off}"

set -g history-limit 20000

bind-key x set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

bind e new-window -n "~/.tmux.conf" "EDITOR=\${EDITOR//mvim/vim} && EDITOR=\${EDITOR//gvim/vim} && \${EDITOR:-vim} ~/.tmux.conf && tmux source ~/.tmux.conf && tmux display \"~/.tmux.conf sourced\""
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# -- display -------------------------------------------------------------------

set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on
set -g display-panes-time 800
set -g display-time 1000
set -g status-interval 5

set -g monitor-activity on
set -g visual-activity off

# -- navigation ----------------------------------------------------------------

bind C-c new-session
bind C-f command-prompt -p find-session 'switch-client -t %%'

bind _ split-window -h
bind - split-window -v
unbind '"'
unbind %

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind > swap-pane -D
bind < swap-pane -U

bind + run 'cut -c3- ~/.tmux.conf | sh -s _maximize_pane "#{session_name}" #D'

bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

unbind n
unbind p
bind -r C-h previous-window
bind -r C-l next-window
bind Tab last-window

# -- copy mode -----------------------------------------------------------------

bind Enter copy-mode

if -b 'command -v xsel > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xsel -i -b"'
if -b '! command -v xsel > /dev/null 2>&1 && command -v xclip > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xclip -i -selection clipboard >/dev/null 2>&1"'
if -b 'command -v pbcopy > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | pbcopy"'
if -b 'command -v reattach-to-user-namespace > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | reattach-to-user-namespace pbcopy"'
if -b 'command -v clip.exe > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | clip.exe"'
if -b '[ -c /dev/clipboard ]' 'bind y run -b "tmux save-buffer - > /dev/clipboard"'

# -- buffers -------------------------------------------------------------------

bind b list-buffers
bind p paste-buffer
bind P choose-buffer

# -- overrides -----------------------------------------------------------------

source -q ~/.tmux.conf.local

# -- statusbar -----------------------------------------------------------------

set -g status-bg '#d7fc03'
set -g status-fg '#1A1A1A'

set -g status-left-length 150
set -g status-right-length 150

set -g status-left "#[fg=#1A1A1A,bg=#d7fc03,bold][#S] #{uptime} / "
set -g status-right "#{prefix_highlight} #[bold] #[fg=#1A1A1A,bg=#d7fc03] #H / #(${HOME}/dotfiles/configs/tmux/kube-tmux.sh)#[fg=#1A1A1A,bg=#d7fc03] / #(${HOME}/dotfiles/configs/tmux/docker-counter.sh) /#{cpu_bg_color} CPU:#{cpu_percentage} #{ram_bg_color} RAM:#{ram_percentage} #[bg=#1A1A1A] 💀 "

setw -g window-status-current-style fg='#ffffff',bg='#1A1A1A'

set -g window-status-format "#[bold] #I) #W "
set -g window-status-current-format "#[bold] #I) #W#{?window_flags, , } "

set-option -g allow-rename on

# -- plugins -------------------------------------------------------------------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'soyuka/tmux-current-pane-hostname'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @prefix_highlight_bg '#d7fc03'
set -g @plugin 'robhurring/tmux-uptime'

run '~/.tmux/plugins/tpm/tpm'
