if [ -d "$HOME/bin" ]; then
  PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ]; then
  PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "${KREW_ROOT:-$HOME/.krew}/bin" ]; then
  PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
fi

if [ -d "/opt/diff-so-fancy" ]; then
  PATH="$PATH:/opt/diff-so-fancy"
fi

if [ -d "$HOME/.local/share/JetBrains/Toolbox/scripts" ]; then
  PATH="$PATH:$HOME/.local/share/JetBrains/Toolbox/scripts"
fi

if [ -d "$HOME/.jdks/openjdk-21/bin" ]; then
  PATH="$PATH:$HOME/.jdks/openjdk-21/bin"
fi

if [ -d "$HOME/.local/kitty.app/bin" ]; then
  PATH="$PATH:$HOME/.local/kitty.app/bin"
fi

if [ -d "$HOME/.functions/" ]; then
  source "$HOME/.functions/zsh_functions"
fi

if [ -f "$HOME/.kubectl_aliases" ]; then
  source "$HOME/.kubectl_aliases"
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    if [ -f "$HOME/.google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/.google-cloud-sdk/path.zsh.inc"; fi
    if [ -f "$HOME/.google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/.google-cloud-sdk/completion.zsh.inc"; fi
fi

export KUBE_EDITOR="nvim"

if [[ -d /opt/homebrew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
  if [[ -f "$HOME/.Brewfile" ]]; then
    export HOMEBREW_BUNDLE_FILE="$HOME/.Brewfile"
  fi
fi

PATH="$PATH:/Library/Frameworks/Python.framework/Versions/3.10/bin"
export PATH="$PATH:/sbin"
export PATH="$PATH:/usr/local/go/bin"
export GO111MODULE=auto

if [ -d "$HOME/source/devops/dev/go" ]; then
  export GOPATH="$HOME/source/devops/dev/go"
  PATH="$PATH:$GOPATH/bin"
fi

source ~/.orbstack/shell/init.zsh 2>/dev/null || :

export GPG_TTY=$(tty)
