if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    export ZSH="/home/$USER/.oh-my-zsh"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    export ZSH="/Users/$USER/.oh-my-zsh"
fi

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  git
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
  web-search
  dirhistory
  gcloud
  helm
  kubectl
  kubectx
  nmap
  httpie
  jira
  tmux
)
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  plugins+=(ubuntu supervisor systemd)
fi

DISABLE_AUTO_UPDATE="false"

source "$ZSH/oh-my-zsh.sh"

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

if [[ "$OSTYPE" == "darwin"* ]]; then
  if type brew &>/dev/null; then
    FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
    autoload -Uz compinit
    compinit
  fi
fi

source "$HOME/.zsh_aliases"

if command -v fzf &>/dev/null; then
  source <(fzf --zsh)
fi
